<?php
$blockobj= $block->getLayout()->createBlock('Ambab\EmiCalculator\Block\Catalog\Product\Price');
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();            
$sku = $_product->getSku();
if($_product->getTypeId() == 'simple'){
    $productqty = $blockobj->getProductSalableQty($sku);
}

// $productqty = $blockobj->getProductSalableQty($sku);

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue) :?>
<div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
    <?php if ($renderLabel) :?>
        <strong class="type"><?= $block->escapeHtml($_attributeLabel) ?></strong>
    <?php endif; ?>
    <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue ?></div>
    <br>
    <strong>
        <?php if(isset($productqty)):?>
            <span style="font-size: 15px;"><?= $productqty ?></span>
            <span> Units left</span>
        <?php endif;?>
    </strong><br>

    <?php if ($_product->gethotproduct()) : ?>
        <span class="hot">This is 🔥 Product</span>
    <?php endif; ?> 
</div>
<?php endif; ?>

